"""Verifier-only path (`pop-verify`, sp1-verifier, no prover) tests.

The heavy fixture (a compressed proof) is generated by `scripts/make_audit_proof.sh`
into `circuits/testdata/audit_proof/`. Tests skip cleanly when the binary or the
fixture is absent.
"""

import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
POP_VERIFY = REPO / "circuits" / "target" / "release" / "pop-verify"
FIXTURE = REPO / "circuits" / "testdata" / "audit_proof"


class TestVerifierOnly(unittest.TestCase):
    @unittest.skipUnless(POP_VERIFY.exists(), "pop-verify not built (cargo build -p pop-verify)")
    def test_compressed_fixture_verifies_fast_and_light(self):
        sidecar = FIXTURE / "proof.verify.json"
        if not sidecar.exists():
            self.skipTest("no compressed fixture; run scripts/make_audit_proof.sh")
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "res.json"
            t0 = time.perf_counter()
            r = subprocess.run([str(POP_VERIFY), "--meta", str(sidecar), "--out", str(out)],
                               capture_output=True, text=True, cwd=str(REPO))
            secs = time.perf_counter() - t0
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            v = json.loads(out.read_text())
            self.assertTrue(v["verified"])
            self.assertEqual(v["proof_mode"], "compressed")
            # public values hash matches the raw file the sidecar points to
            meta = json.loads(sidecar.read_text())
            pv = Path(meta["public_values_file"]).read_bytes()
            self.assertEqual(v["public_values_sha256"], hashlib.sha256(pv).hexdigest())
            # verifier-only: no prover → should be quick (generous bound for CI)
            self.assertLess(secs, 20, f"pop-verify took {secs:.1f}s (unexpectedly slow)")

    @unittest.skipUnless(POP_VERIFY.exists(), "pop-verify not built")
    def test_core_mode_is_rejected_with_clear_message(self):
        with tempfile.TemporaryDirectory() as tmp:
            meta = Path(tmp) / "fake.verify.json"
            meta.write_text(json.dumps({"proof_mode": "core", "proof_bytes_file": "x",
                                        "public_values_file": "y"}))
            r = subprocess.run([str(POP_VERIFY), "--meta", str(meta)],
                               capture_output=True, text=True, cwd=str(REPO))
            self.assertEqual(r.returncode, 3)
            self.assertIn("not verifier-only verifiable", r.stderr)

    @unittest.skipUnless(POP_VERIFY.exists(), "pop-verify not built")
    def test_pop_verify_does_not_need_sp1_env(self):
        """No prover construction: it must not require SP1_PROVER or the prover deps."""
        sidecar = FIXTURE / "proof.verify.json"
        if not sidecar.exists():
            self.skipTest("no compressed fixture")
        env = {k: v for k, v in __import__("os").environ.items() if k != "SP1_PROVER"}
        r = subprocess.run([str(POP_VERIFY), "--meta", str(sidecar)],
                           capture_output=True, text=True, cwd=str(REPO), env=env)
        self.assertEqual(r.returncode, 0, r.stderr)


class TestVerifierOnlySelection(unittest.TestCase):
    """The verifier-only fast-path selection is a pure function (tested offline)."""

    def test_prefer_verifier_only_requires_binary_and_sidecar(self):
        sys.path.insert(0, str(REPO / "scripts"))
        from verify_session import prefer_verifier_only

        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            proof = tmp / "proof.bin"
            proof.write_bytes(b"x")
            binary = tmp / "pop-verify"
            # neither binary nor sidecar → no
            self.assertFalse(prefer_verifier_only(proof, binary))
            # sidecar only → still no (binary missing)
            Path(str(proof) + ".verify.json").write_text("{}")
            self.assertFalse(prefer_verifier_only(proof, binary))
            # both → yes
            binary.write_text("#!/bin/sh\n")
            self.assertTrue(prefer_verifier_only(proof, binary))


if __name__ == "__main__":
    unittest.main()
